// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: protos/kv.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LogEntry represents an entry of a record intended to be saved in
// the append-only log file
type LogEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// used as a reference to identify entry
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// data to be saved
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// used to detect corrupted data
	Checksum uint32 `protobuf:"varint,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	// used to represent tombstone
	IsDeleted     bool `protobuf:"varint,4,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_protos_kv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_protos_kv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_protos_kv_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LogEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *LogEntry) GetChecksum() uint32 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

func (x *LogEntry) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

type SnapshotState struct {
	state                protoimpl.MessageState    `protogen:"open.v1"`
	LogEntryIndexesByKey map[string]*LogEntryIndex `protobuf:"bytes,1,rep,name=log_entry_indexes_by_key,json=logEntryIndexesByKey,proto3" json:"log_entry_indexes_by_key,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SnapshotState) Reset() {
	*x = SnapshotState{}
	mi := &file_protos_kv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotState) ProtoMessage() {}

func (x *SnapshotState) ProtoReflect() protoreflect.Message {
	mi := &file_protos_kv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotState.ProtoReflect.Descriptor instead.
func (*SnapshotState) Descriptor() ([]byte, []int) {
	return file_protos_kv_proto_rawDescGZIP(), []int{1}
}

func (x *SnapshotState) GetLogEntryIndexesByKey() map[string]*LogEntryIndex {
	if x != nil {
		return x.LogEntryIndexesByKey
	}
	return nil
}

type SnapshotEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *SnapshotState         `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Checksum      uint32                 `protobuf:"varint,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotEntry) Reset() {
	*x = SnapshotEntry{}
	mi := &file_protos_kv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotEntry) ProtoMessage() {}

func (x *SnapshotEntry) ProtoReflect() protoreflect.Message {
	mi := &file_protos_kv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotEntry.ProtoReflect.Descriptor instead.
func (*SnapshotEntry) Descriptor() ([]byte, []int) {
	return file_protos_kv_proto_rawDescGZIP(), []int{2}
}

func (x *SnapshotEntry) GetSnapshot() *SnapshotState {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *SnapshotEntry) GetChecksum() uint32 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

func (x *SnapshotEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SnapshotEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type LogEntryIndex struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// used as a reference to identify entry
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// offset of where log entry is located in the segment file on disk
	Offset int64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// size of the entry
	EntrySize int64 `protobuf:"varint,3,opt,name=entry_size,json=entrySize,proto3" json:"entry_size,omitempty"`
	// filename of the segment file that the logentry is stored
	SegmentFilename string `protobuf:"bytes,4,opt,name=segment_filename,json=segmentFilename,proto3" json:"segment_filename,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LogEntryIndex) Reset() {
	*x = LogEntryIndex{}
	mi := &file_protos_kv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntryIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntryIndex) ProtoMessage() {}

func (x *LogEntryIndex) ProtoReflect() protoreflect.Message {
	mi := &file_protos_kv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntryIndex.ProtoReflect.Descriptor instead.
func (*LogEntryIndex) Descriptor() ([]byte, []int) {
	return file_protos_kv_proto_rawDescGZIP(), []int{3}
}

func (x *LogEntryIndex) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LogEntryIndex) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *LogEntryIndex) GetEntrySize() int64 {
	if x != nil {
		return x.EntrySize
	}
	return 0
}

func (x *LogEntryIndex) GetSegmentFilename() string {
	if x != nil {
		return x.SegmentFilename
	}
	return ""
}

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_protos_kv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_kv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_protos_kv_proto_rawDescGZIP(), []int{4}
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_protos_kv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_kv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_protos_kv_proto_rawDescGZIP(), []int{5}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_protos_kv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_kv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_protos_kv_proto_rawDescGZIP(), []int{6}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_protos_kv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_kv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_protos_kv_proto_rawDescGZIP(), []int{7}
}

func (x *GetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_protos_kv_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_kv_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_protos_kv_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_protos_kv_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_kv_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_protos_kv_proto_rawDescGZIP(), []int{9}
}

type BatchSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*SetRequest          `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSetRequest) Reset() {
	*x = BatchSetRequest{}
	mi := &file_protos_kv_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSetRequest) ProtoMessage() {}

func (x *BatchSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_kv_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSetRequest.ProtoReflect.Descriptor instead.
func (*BatchSetRequest) Descriptor() ([]byte, []int) {
	return file_protos_kv_proto_rawDescGZIP(), []int{10}
}

func (x *BatchSetRequest) GetRequests() []*SetRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type BatchSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSetResponse) Reset() {
	*x = BatchSetResponse{}
	mi := &file_protos_kv_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSetResponse) ProtoMessage() {}

func (x *BatchSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_kv_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSetResponse.ProtoReflect.Descriptor instead.
func (*BatchSetResponse) Descriptor() ([]byte, []int) {
	return file_protos_kv_proto_rawDescGZIP(), []int{11}
}

type BatchGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*GetRequest          `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetRequest) Reset() {
	*x = BatchGetRequest{}
	mi := &file_protos_kv_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetRequest) ProtoMessage() {}

func (x *BatchGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_kv_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetRequest.ProtoReflect.Descriptor instead.
func (*BatchGetRequest) Descriptor() ([]byte, []int) {
	return file_protos_kv_proto_rawDescGZIP(), []int{12}
}

func (x *BatchGetRequest) GetRequests() []*GetRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type BatchGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*GetResponse         `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetResponse) Reset() {
	*x = BatchGetResponse{}
	mi := &file_protos_kv_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetResponse) ProtoMessage() {}

func (x *BatchGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_kv_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetResponse.ProtoReflect.Descriptor instead.
func (*BatchGetResponse) Descriptor() ([]byte, []int) {
	return file_protos_kv_proto_rawDescGZIP(), []int{13}
}

func (x *BatchGetResponse) GetResponses() []*GetResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

type BatchDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*DeleteRequest       `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDeleteRequest) Reset() {
	*x = BatchDeleteRequest{}
	mi := &file_protos_kv_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDeleteRequest) ProtoMessage() {}

func (x *BatchDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_kv_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDeleteRequest.ProtoReflect.Descriptor instead.
func (*BatchDeleteRequest) Descriptor() ([]byte, []int) {
	return file_protos_kv_proto_rawDescGZIP(), []int{14}
}

func (x *BatchDeleteRequest) GetRequests() []*DeleteRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type BatchDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDeleteResponse) Reset() {
	*x = BatchDeleteResponse{}
	mi := &file_protos_kv_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDeleteResponse) ProtoMessage() {}

func (x *BatchDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_kv_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDeleteResponse.ProtoReflect.Descriptor instead.
func (*BatchDeleteResponse) Descriptor() ([]byte, []int) {
	return file_protos_kv_proto_rawDescGZIP(), []int{15}
}

var File_protos_kv_proto protoreflect.FileDescriptor

const file_protos_kv_proto_rawDesc = "" +
	"\n" +
	"\x0fprotos/kv.proto\x12\x04core\x1a\x1fgoogle/protobuf/timestamp.proto\"m\n" +
	"\bLogEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\rR\bchecksum\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x04 \x01(\bR\tisDeleted\"\xd4\x01\n" +
	"\rSnapshotState\x12e\n" +
	"\x18log_entry_indexes_by_key\x18\x01 \x03(\v2-.core.SnapshotState.LogEntryIndexesByKeyEntryR\x14logEntryIndexesByKey\x1a\\\n" +
	"\x19LogEntryIndexesByKeyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.core.LogEntryIndexR\x05value:\x028\x01\"\xa6\x01\n" +
	"\rSnapshotEntry\x12/\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x13.core.SnapshotStateR\bsnapshot\x12\x1a\n" +
	"\bchecksum\x18\x02 \x01(\rR\bchecksum\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x83\x01\n" +
	"\rLogEntryIndex\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x1d\n" +
	"\n" +
	"entry_size\x18\x03 \x01(\x03R\tentrySize\x12)\n" +
	"\x10segment_filename\x18\x04 \x01(\tR\x0fsegmentFilename\"4\n" +
	"\n" +
	"SetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\r\n" +
	"\vSetResponse\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"#\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\x10\n" +
	"\x0eDeleteResponse\"?\n" +
	"\x0fBatchSetRequest\x12,\n" +
	"\brequests\x18\x01 \x03(\v2\x10.core.SetRequestR\brequests\"\x12\n" +
	"\x10BatchSetResponse\"?\n" +
	"\x0fBatchGetRequest\x12,\n" +
	"\brequests\x18\x01 \x03(\v2\x10.core.GetRequestR\brequests\"C\n" +
	"\x10BatchGetResponse\x12/\n" +
	"\tresponses\x18\x01 \x03(\v2\x11.core.GetResponseR\tresponses\"E\n" +
	"\x12BatchDeleteRequest\x12/\n" +
	"\brequests\x18\x01 \x03(\v2\x13.core.DeleteRequestR\brequests\"\x15\n" +
	"\x13BatchDeleteResponse2\xcb\x02\n" +
	"\x02KV\x12*\n" +
	"\x03Set\x12\x10.core.SetRequest\x1a\x11.core.SetResponse\x12*\n" +
	"\x03Get\x12\x10.core.GetRequest\x1a\x11.core.GetResponse\x123\n" +
	"\x06Delete\x12\x13.core.DeleteRequest\x1a\x14.core.DeleteResponse\x129\n" +
	"\bBatchSet\x12\x15.core.BatchSetRequest\x1a\x16.core.BatchSetResponse\x129\n" +
	"\bBatchGet\x12\x15.core.BatchGetRequest\x1a\x16.core.BatchGetResponse\x12B\n" +
	"\vBatchDelete\x12\x18.core.BatchDeleteRequest\x1a\x19.core.BatchDeleteResponseB\vZ\tkv/protosb\x06proto3"

var (
	file_protos_kv_proto_rawDescOnce sync.Once
	file_protos_kv_proto_rawDescData []byte
)

func file_protos_kv_proto_rawDescGZIP() []byte {
	file_protos_kv_proto_rawDescOnce.Do(func() {
		file_protos_kv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_kv_proto_rawDesc), len(file_protos_kv_proto_rawDesc)))
	})
	return file_protos_kv_proto_rawDescData
}

var file_protos_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_protos_kv_proto_goTypes = []any{
	(*LogEntry)(nil),              // 0: core.LogEntry
	(*SnapshotState)(nil),         // 1: core.SnapshotState
	(*SnapshotEntry)(nil),         // 2: core.SnapshotEntry
	(*LogEntryIndex)(nil),         // 3: core.LogEntryIndex
	(*SetRequest)(nil),            // 4: core.SetRequest
	(*SetResponse)(nil),           // 5: core.SetResponse
	(*GetRequest)(nil),            // 6: core.GetRequest
	(*GetResponse)(nil),           // 7: core.GetResponse
	(*DeleteRequest)(nil),         // 8: core.DeleteRequest
	(*DeleteResponse)(nil),        // 9: core.DeleteResponse
	(*BatchSetRequest)(nil),       // 10: core.BatchSetRequest
	(*BatchSetResponse)(nil),      // 11: core.BatchSetResponse
	(*BatchGetRequest)(nil),       // 12: core.BatchGetRequest
	(*BatchGetResponse)(nil),      // 13: core.BatchGetResponse
	(*BatchDeleteRequest)(nil),    // 14: core.BatchDeleteRequest
	(*BatchDeleteResponse)(nil),   // 15: core.BatchDeleteResponse
	nil,                           // 16: core.SnapshotState.LogEntryIndexesByKeyEntry
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
}
var file_protos_kv_proto_depIdxs = []int32{
	16, // 0: core.SnapshotState.log_entry_indexes_by_key:type_name -> core.SnapshotState.LogEntryIndexesByKeyEntry
	1,  // 1: core.SnapshotEntry.snapshot:type_name -> core.SnapshotState
	17, // 2: core.SnapshotEntry.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 3: core.BatchSetRequest.requests:type_name -> core.SetRequest
	6,  // 4: core.BatchGetRequest.requests:type_name -> core.GetRequest
	7,  // 5: core.BatchGetResponse.responses:type_name -> core.GetResponse
	8,  // 6: core.BatchDeleteRequest.requests:type_name -> core.DeleteRequest
	3,  // 7: core.SnapshotState.LogEntryIndexesByKeyEntry.value:type_name -> core.LogEntryIndex
	4,  // 8: core.KV.Set:input_type -> core.SetRequest
	6,  // 9: core.KV.Get:input_type -> core.GetRequest
	8,  // 10: core.KV.Delete:input_type -> core.DeleteRequest
	10, // 11: core.KV.BatchSet:input_type -> core.BatchSetRequest
	12, // 12: core.KV.BatchGet:input_type -> core.BatchGetRequest
	14, // 13: core.KV.BatchDelete:input_type -> core.BatchDeleteRequest
	5,  // 14: core.KV.Set:output_type -> core.SetResponse
	7,  // 15: core.KV.Get:output_type -> core.GetResponse
	9,  // 16: core.KV.Delete:output_type -> core.DeleteResponse
	11, // 17: core.KV.BatchSet:output_type -> core.BatchSetResponse
	13, // 18: core.KV.BatchGet:output_type -> core.BatchGetResponse
	15, // 19: core.KV.BatchDelete:output_type -> core.BatchDeleteResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_protos_kv_proto_init() }
func file_protos_kv_proto_init() {
	if File_protos_kv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_kv_proto_rawDesc), len(file_protos_kv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_kv_proto_goTypes,
		DependencyIndexes: file_protos_kv_proto_depIdxs,
		MessageInfos:      file_protos_kv_proto_msgTypes,
	}.Build()
	File_protos_kv_proto = out.File
	file_protos_kv_proto_goTypes = nil
	file_protos_kv_proto_depIdxs = nil
}
