on: push
name: workflow
jobs:
  checks:
    name: test workflow
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    # - name: test stage
    #   uses: cedrickring/golang-action@1.6.0
    #   with: 
    #     args: make test
    #   env:
    #     GO111MODULE: "on"

    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16.5' # The Go version to download (if necessary) and use.
    - run: make test
